// <auto-generated />
using System;
using BarberShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberShop.Migrations
{
    [DbContext(typeof(BarberShopContext))]
    [Migration("20231210091012_fix_v1")]
    partial class fix_v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BarberShop.Entity.Address", b =>
                {
                    b.Property<int>("addressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("addressID"), 1L, 1);

                    b.Property<int>("cityID")
                        .HasColumnType("int");

                    b.Property<string>("currentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("addressID");

                    b.HasIndex("cityID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("BarberShop.Entity.Booking", b =>
                {
                    b.Property<int>("bookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingID"), 1L, 1);

                    b.Property<int>("customerID")
                        .HasColumnType("int");

                    b.Property<int>("payID")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("startTime")
                        .HasColumnType("time");

                    b.HasKey("bookingID");

                    b.HasIndex("customerID");

                    b.HasIndex("payID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BarberShop.Entity.BookingService", b =>
                {
                    b.Property<int>("bookingServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingServiceID"), 1L, 1);

                    b.Property<int>("bookingID")
                        .HasColumnType("int");

                    b.Property<int>("serviceID")
                        .HasColumnType("int");

                    b.HasKey("bookingServiceID");

                    b.HasIndex("bookingID");

                    b.HasIndex("serviceID");

                    b.ToTable("BookingsService");
                });

            modelBuilder.Entity("BarberShop.Entity.BookingStateDescription", b =>
                {
                    b.Property<int>("stateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stateID"), 1L, 1);

                    b.Property<int>("bookingID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stateID");

                    b.HasIndex("bookingID")
                        .IsUnique();

                    b.ToTable("BookingStateDescription");
                });

            modelBuilder.Entity("BarberShop.Entity.Category", b =>
                {
                    b.Property<int>("cateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cateID"), 1L, 1);

                    b.Property<string>("cateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cateID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("BarberShop.Entity.City", b =>
                {
                    b.Property<int>("cityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cityID"), 1L, 1);

                    b.Property<string>("cityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("countryID")
                        .HasColumnType("int");

                    b.HasKey("cityID");

                    b.HasIndex("countryID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BarberShop.Entity.Country", b =>
                {
                    b.Property<int>("countryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("countryID"), 1L, 1);

                    b.Property<string>("countryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("countryID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("BarberShop.Entity.Customer", b =>
                {
                    b.Property<int>("customerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerID"), 1L, 1);

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("customerID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("BarberShop.Entity.CustomerAddress", b =>
                {
                    b.Property<int>("cusAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cusAddressId"), 1L, 1);

                    b.Property<int>("addressID")
                        .HasColumnType("int");

                    b.Property<int>("customerID")
                        .HasColumnType("int");

                    b.HasKey("cusAddressId");

                    b.HasIndex("addressID");

                    b.HasIndex("customerID");

                    b.ToTable("CustomerAddress");
                });

            modelBuilder.Entity("BarberShop.Entity.CustomerNotification", b =>
                {
                    b.Property<int>("cNotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cNotificationID"), 1L, 1);

                    b.Property<int>("customerID")
                        .HasColumnType("int");

                    b.Property<int>("notiID")
                        .HasColumnType("int");

                    b.HasKey("cNotificationID");

                    b.HasIndex("customerID");

                    b.HasIndex("notiID");

                    b.ToTable("CustomerNotification");
                });

            modelBuilder.Entity("BarberShop.Entity.Employee", b =>
                {
                    b.Property<int>("employeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeID"), 1L, 1);

                    b.Property<int>("addressID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storeID")
                        .HasColumnType("int");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.Property<DateTime>("wordDay")
                        .HasColumnType("datetime2");

                    b.HasKey("employeID");

                    b.HasIndex("addressID");

                    b.HasIndex("storeID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BarberShop.Entity.Evaluate", b =>
                {
                    b.Property<int>("evaluateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("evaluateID"), 1L, 1);

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("storeID")
                        .HasColumnType("int");

                    b.HasKey("evaluateID");

                    b.HasIndex("customerID");

                    b.HasIndex("storeID");

                    b.ToTable("Evaluate");
                });

            modelBuilder.Entity("BarberShop.Entity.LocationStore", b =>
                {
                    b.Property<int>("locationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("locationID"), 1L, 1);

                    b.Property<int>("cityID")
                        .HasColumnType("int");

                    b.Property<string>("currentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storeID")
                        .HasColumnType("int");

                    b.Property<string>("subDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("locationID");

                    b.HasIndex("cityID");

                    b.HasIndex("storeID");

                    b.ToTable("LocationStore");
                });

            modelBuilder.Entity("BarberShop.Entity.Notification", b =>
                {
                    b.Property<int>("notiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notiID"), 1L, 1);

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("notiContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notiTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("notiID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BarberShop.Entity.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderID"), 1L, 1);

                    b.Property<int>("customerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("orderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("payID")
                        .HasColumnType("int");

                    b.HasKey("orderID");

                    b.HasIndex("customerID");

                    b.HasIndex("payID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BarberShop.Entity.Payment", b =>
                {
                    b.Property<int>("payID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("payID"), 1L, 1);

                    b.Property<string>("payMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("payStatus")
                        .HasColumnType("bit");

                    b.HasKey("payID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("BarberShop.Entity.Producer", b =>
                {
                    b.Property<int>("producerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("producerID"), 1L, 1);

                    b.Property<int>("addressID")
                        .HasColumnType("int");

                    b.Property<string>("numberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("producerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("producerID");

                    b.HasIndex("addressID")
                        .IsUnique();

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("BarberShop.Entity.Product", b =>
                {
                    b.Property<int>("proID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proID"), 1L, 1);

                    b.Property<int>("cateID")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("proDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("producerID")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("warehouseID")
                        .HasColumnType("int");

                    b.HasKey("proID");

                    b.HasIndex("cateID");

                    b.HasIndex("producerID");

                    b.HasIndex("warehouseID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BarberShop.Entity.ProductOrder", b =>
                {
                    b.Property<int>("proOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proOrderID"), 1L, 1);

                    b.Property<int>("orderID")
                        .HasColumnType("int");

                    b.Property<int>("proID")
                        .HasColumnType("int");

                    b.Property<int>("proOrderQuantity")
                        .HasColumnType("int");

                    b.HasKey("proOrderID");

                    b.HasIndex("orderID");

                    b.HasIndex("proID");

                    b.ToTable("ProductOrder");
                });

            modelBuilder.Entity("BarberShop.Entity.Role", b =>
                {
                    b.Property<int>("roleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleID"), 1L, 1);

                    b.Property<string>("roleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("BarberShop.Entity.ServiceCategory", b =>
                {
                    b.Property<int>("serCateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serCateID"), 1L, 1);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serCateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("serCateID");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("BarberShop.Entity.ServiceManagement", b =>
                {
                    b.Property<int>("serManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serManagerID"), 1L, 1);

                    b.Property<int>("serID")
                        .HasColumnType("int");

                    b.Property<int>("storeID")
                        .HasColumnType("int");

                    b.HasKey("serManagerID");

                    b.HasIndex("serID");

                    b.HasIndex("storeID");

                    b.ToTable("ServiceManagement");
                });

            modelBuilder.Entity("BarberShop.Entity.Services", b =>
                {
                    b.Property<int>("serID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serID"), 1L, 1);

                    b.Property<int>("serCateID")
                        .HasColumnType("int");

                    b.Property<string>("serDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("serPrice")
                        .HasColumnType("real");

                    b.HasKey("serID");

                    b.HasIndex("serCateID");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("BarberShop.Entity.Store", b =>
                {
                    b.Property<int>("storeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("storeID"), 1L, 1);

                    b.Property<string>("numberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("workingHourID")
                        .HasColumnType("int");

                    b.HasKey("storeID");

                    b.HasIndex("workingHourID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("BarberShop.Entity.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("roleID")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userID");

                    b.HasIndex("roleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarberShop.Entity.Warehouse", b =>
                {
                    b.Property<int>("warehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("warehouseID"), 1L, 1);

                    b.Property<int>("addressID")
                        .HasColumnType("int");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<int>("storeID")
                        .HasColumnType("int");

                    b.Property<float>("totalAsset")
                        .HasColumnType("real");

                    b.Property<string>("warehouseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("warehouseID");

                    b.HasIndex("addressID")
                        .IsUnique();

                    b.HasIndex("storeID");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("BarberShop.Entity.WorkingHour", b =>
                {
                    b.Property<int>("workingHourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workingHourID"), 1L, 1);

                    b.Property<TimeSpan>("endTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("startTime")
                        .HasColumnType("time");

                    b.HasKey("workingHourID");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("BarberShop.Entity.Address", b =>
                {
                    b.HasOne("BarberShop.Entity.City", "city")
                        .WithMany("addresses")
                        .HasForeignKey("cityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("BarberShop.Entity.Booking", b =>
                {
                    b.HasOne("BarberShop.Entity.Customer", "customer")
                        .WithMany("Bookings")
                        .HasForeignKey("customerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Payment", "payment")
                        .WithMany()
                        .HasForeignKey("payID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("BarberShop.Entity.BookingService", b =>
                {
                    b.HasOne("BarberShop.Entity.Booking", "booking")
                        .WithMany("bookingServices")
                        .HasForeignKey("bookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Services", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("serviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("booking");
                });

            modelBuilder.Entity("BarberShop.Entity.BookingStateDescription", b =>
                {
                    b.HasOne("BarberShop.Entity.Booking", "Booking")
                        .WithOne("BookingSateDescription")
                        .HasForeignKey("BarberShop.Entity.BookingStateDescription", "bookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BarberShop.Entity.City", b =>
                {
                    b.HasOne("BarberShop.Entity.Country", "country")
                        .WithMany("city")
                        .HasForeignKey("countryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("BarberShop.Entity.Customer", b =>
                {
                    b.HasOne("BarberShop.Entity.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("BarberShop.Entity.Customer", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberShop.Entity.CustomerAddress", b =>
                {
                    b.HasOne("BarberShop.Entity.Address", "Address")
                        .WithMany("customers")
                        .HasForeignKey("addressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Customer", "Customer")
                        .WithMany("addresses")
                        .HasForeignKey("customerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BarberShop.Entity.CustomerNotification", b =>
                {
                    b.HasOne("BarberShop.Entity.Customer", "Customer")
                        .WithMany("CustomerNotifications")
                        .HasForeignKey("customerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Notification", "Notification")
                        .WithMany("customerNotifications")
                        .HasForeignKey("notiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("BarberShop.Entity.Employee", b =>
                {
                    b.HasOne("BarberShop.Entity.Address", "Address")
                        .WithMany("Employees")
                        .HasForeignKey("addressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Store", "Store")
                        .WithMany("employees")
                        .HasForeignKey("storeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.User", "user")
                        .WithOne("Employee")
                        .HasForeignKey("BarberShop.Entity.Employee", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Store");

                    b.Navigation("user");
                });

            modelBuilder.Entity("BarberShop.Entity.Evaluate", b =>
                {
                    b.HasOne("BarberShop.Entity.Customer", "customer")
                        .WithMany("Evaluations")
                        .HasForeignKey("customerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Store", "store")
                        .WithMany("evaluates")
                        .HasForeignKey("storeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("store");
                });

            modelBuilder.Entity("BarberShop.Entity.LocationStore", b =>
                {
                    b.HasOne("BarberShop.Entity.City", "city")
                        .WithMany("cities")
                        .HasForeignKey("cityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Store", "Store")
                        .WithMany("locationStore")
                        .HasForeignKey("storeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("city");
                });

            modelBuilder.Entity("BarberShop.Entity.Order", b =>
                {
                    b.HasOne("BarberShop.Entity.Customer", "customer")
                        .WithMany("Orders")
                        .HasForeignKey("customerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("payID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("BarberShop.Entity.Producer", b =>
                {
                    b.HasOne("BarberShop.Entity.Address", "Address")
                        .WithOne("Producer")
                        .HasForeignKey("BarberShop.Entity.Producer", "addressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BarberShop.Entity.Product", b =>
                {
                    b.HasOne("BarberShop.Entity.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("cateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Producer", "Producer")
                        .WithMany("Product")
                        .HasForeignKey("producerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Warehouse", "Warehouse")
                        .WithMany("products")
                        .HasForeignKey("warehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");

                    b.Navigation("Warehouse");

                    b.Navigation("category");
                });

            modelBuilder.Entity("BarberShop.Entity.ProductOrder", b =>
                {
                    b.HasOne("BarberShop.Entity.Order", "Order")
                        .WithMany("ProductOrders")
                        .HasForeignKey("orderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Product", "Product")
                        .WithMany("ProductOrders")
                        .HasForeignKey("proID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BarberShop.Entity.ServiceManagement", b =>
                {
                    b.HasOne("BarberShop.Entity.Services", "Service")
                        .WithMany("ServiceManagement")
                        .HasForeignKey("serID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Store", "Store")
                        .WithMany("serviceManagement")
                        .HasForeignKey("storeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BarberShop.Entity.Services", b =>
                {
                    b.HasOne("BarberShop.Entity.ServiceCategory", "ServiceCategory")
                        .WithMany("services")
                        .HasForeignKey("serCateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("BarberShop.Entity.Store", b =>
                {
                    b.HasOne("BarberShop.Entity.WorkingHour", "workingHour")
                        .WithMany("stores")
                        .HasForeignKey("workingHourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("workingHour");
                });

            modelBuilder.Entity("BarberShop.Entity.User", b =>
                {
                    b.HasOne("BarberShop.Entity.Role", "Role")
                        .WithMany("users")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BarberShop.Entity.Warehouse", b =>
                {
                    b.HasOne("BarberShop.Entity.Address", "Address")
                        .WithOne("Warehouse")
                        .HasForeignKey("BarberShop.Entity.Warehouse", "addressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberShop.Entity.Store", "Store")
                        .WithMany("warehouse")
                        .HasForeignKey("storeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BarberShop.Entity.Address", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Producer");

                    b.Navigation("Warehouse");

                    b.Navigation("customers");
                });

            modelBuilder.Entity("BarberShop.Entity.Booking", b =>
                {
                    b.Navigation("BookingSateDescription");

                    b.Navigation("bookingServices");
                });

            modelBuilder.Entity("BarberShop.Entity.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("BarberShop.Entity.City", b =>
                {
                    b.Navigation("addresses");

                    b.Navigation("cities");
                });

            modelBuilder.Entity("BarberShop.Entity.Country", b =>
                {
                    b.Navigation("city");
                });

            modelBuilder.Entity("BarberShop.Entity.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CustomerNotifications");

                    b.Navigation("Evaluations");

                    b.Navigation("Orders");

                    b.Navigation("addresses");
                });

            modelBuilder.Entity("BarberShop.Entity.Notification", b =>
                {
                    b.Navigation("customerNotifications");
                });

            modelBuilder.Entity("BarberShop.Entity.Order", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("BarberShop.Entity.Producer", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("BarberShop.Entity.Product", b =>
                {
                    b.Navigation("ProductOrders");
                });

            modelBuilder.Entity("BarberShop.Entity.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("BarberShop.Entity.ServiceCategory", b =>
                {
                    b.Navigation("services");
                });

            modelBuilder.Entity("BarberShop.Entity.Services", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("ServiceManagement");
                });

            modelBuilder.Entity("BarberShop.Entity.Store", b =>
                {
                    b.Navigation("employees");

                    b.Navigation("evaluates");

                    b.Navigation("locationStore");

                    b.Navigation("serviceManagement");

                    b.Navigation("warehouse");
                });

            modelBuilder.Entity("BarberShop.Entity.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BarberShop.Entity.Warehouse", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("BarberShop.Entity.WorkingHour", b =>
                {
                    b.Navigation("stores");
                });
#pragma warning restore 612, 618
        }
    }
}
